server:
  port: 8080

jwt:
  secret: sorbet-secret-key-jwt-1234567890

spring:
  application:
    name: Sorbet
  datasource:
    url: jdbc:mysql://localhost:3306/sorbet?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sorbet
    password: Sorbet123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  # application.yml
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false

