server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sorbet?useSSL=false&serverTimezone=Asia/Seoul
    username: sorbet
    password: sorbet123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    cache: false
